apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
spec:
  replicas: 5
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: container1
          image: minikube1707/myweb
          ports:
            - containerPort: 80
              protocol: TCP